### ISSUE TITLE
New Use Cases (in Wiki) (Part 5)

### ISSUE THREAD

**Issue by tiegan** [CMPUT301F16T10/Drivr#12]
- [x] US 1.09.01 (car details)

- [x] US 1.10.01 (ratings)

- [x] US 1.11.01 (ratings)

- [x] US 03.04.01 (car details)

- [x] US 04.03.01 (price search)

- [x] US 04.04.01 (addresses)

- [x] US 04.05.01 (addresses)

All need to include:
- Add actors
- Add triggers
- Add preconditions (if applicable)
- Add basic flow of events
- Add postconditions (if applicable)
- Add alternate flow of events (if applicable)

**Comment by Daniel-DY-Lee** [comment]
Included new use cases and added definition for "vehicle" in the glossary
